language=en
startWithSystem=false
minimizeToTrayOnClose=true
minimizeToTrayOnStartup=false
updateBridgesOnStartup=false
directTimeoutSeconds=75
bridgeTimeoutSeconds=120
healthCheckSeconds=20
torLogLevel=notice
hideNoisyBridgeWarnings=true
directSocksPort=9060
directHttpPort=19060
vanillaSocksPort=9061
vanillaHttpPort=19061
obfs4SocksPort=9062
obfs4HttpPort=19062
snowflakeSocksPort=9063
snowflakeHttpPort=19063
meekSocksPort=9064
meekHttpPort=19064
webtunnelSocksPort=9065
webtunnelHttpPort=19065
packagedTorSocksPortBase=9260
developmentTorSocksPortBase=9360
packagedControlPortBase=30060
developmentControlPortBase=31060
