localBridgeRoot=/AGTY/WORK/work/AGTY/projects/DeltaTorUbuntu/!files/Delta-Tor/bridges
rawBase=https://raw.githubusercontent.com/Delta-Kronecker/Tor-Bridges-Collector/refs/heads/main/bridge/
entry.1=Vanilla Tested|VANILLA_BRIDGE|Tested_and_Active_vanilla_IPv4.txt|vanilla_tested.txt
entry.2=obfs4 Tested|OBFS4|Tested_and_Active_obfs4_IPv4.txt|obfs4_tested.txt
entry.3=WebTunnel Tested|WEBTUNNEL|Tested_and_Active_webtunnel_IPv4.txt|webtunnel_tested.txt
entry.4=Vanilla Fresh IPv4|VANILLA_BRIDGE|Fresh_72h_vanilla_IPv4.txt|vanilla_72h.txt
entry.5=Vanilla Fresh IPv6|VANILLA_BRIDGE|Fresh_72h_vanilla_IPv6.txt|vanilla_ipv6_72h.txt
entry.6=obfs4 Fresh IPv4|OBFS4|Fresh_72h_obfs4_IPv4.txt|obfs4_72h.txt
entry.7=obfs4 Fresh IPv6|OBFS4|Fresh_72h_obfs4_IPv6.txt|obfs4_ipv6_72h.txt
entry.8=WebTunnel Fresh IPv4|WEBTUNNEL|Fresh_72h_webtunnel_IPv4.txt|webtunnel_72h.txt
entry.9=WebTunnel Fresh IPv6|WEBTUNNEL|Fresh_72h_webtunnel_IPv6.txt|webtunnel_ipv6_72h.txt
entry.10=Vanilla Archive IPv4|VANILLA_BRIDGE|Full_Archive_vanilla_IPv4.txt|vanilla.txt
entry.11=Vanilla Archive IPv6|VANILLA_BRIDGE|Full_Archive_vanilla_IPv6.txt|vanilla_ipv6.txt
entry.12=obfs4 Archive IPv4|OBFS4|Full_Archive_obfs4_IPv4.txt|obfs4.txt
entry.13=obfs4 Archive IPv6|OBFS4|Full_Archive_obfs4_IPv6.txt|obfs4_ipv6.txt
entry.14=WebTunnel Archive IPv4|WEBTUNNEL|Full_Archive_webtunnel_IPv4.txt|webtunnel.txt
entry.15=WebTunnel Archive IPv6|WEBTUNNEL|Full_Archive_webtunnel_IPv6.txt|webtunnel_ipv6.txt
